
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'bq_adwords'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'tap_adwords'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  tap_adwords:
      # Applies to all files under models/example/
      production:
          +materialized: table
vars: 
    t_campaignStats: '`thrivehive.p_CampaignStats_4805394795`'
    t_campaign: '`thrivehive.p_Campaign_4805394795`'
    t_ads: '`thrivehive.p_Ad_4805394795`'
    t_adStats: '`thrivehive.p_AdStats_4805394795`'
    t_campaignConv: '`thrivehive.p_CampaignConversionStats_4805394795`'
    t_adGroupStats: '`thrivehive.p_AdGroupStats_4805394795`'
    t_adGroup: '`thrivehive.p_AdGroup_4805394795`'
    t_adGroupConv: '`thrivehive.p_AdGroupConversionStats_4805394795`'
    convName1: '"name of first conversion"'
    convName2: '"name of second conversion"'
    convName3: '"name of third conversion"'

